spring:
 data:
   mongodb:
     database: keepnote
     port: 27017
     host: localhost
 application:
  name: NewsSourceService
server:
 port: 8083
 
eureka:
 client:
  service-url:
   defaultZone: http://eurekaserver:password@localhost:8761/eureka/